window:
  title: Alacritty
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.97
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

cursor:
  style:
    shape: Block
    blinking: Off
  vi_mode_style:
    shape: Block
    blinking: Off

font:
  size: 14
  normal:
    family: FiraMono Nerd Font
    style: Medium

key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }

# ------------------------------------------ #
# tokyo night theme
colors:
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'
